name: Setup Elemental CLI
description: |
  This action installs elemental-cli.
inputs:
  repository:
    description: Repository to download from
    required: false
    default: rancher/elemental-cli
  version:
    description: Version to install
    required: false
    default: v0.2.1
  os:
    description: Os to install for
    required: false
    default: Linux
  arch:
    description: Arch to install
    required: false
    default: x86_64

runs:
  using: "composite"

  steps:
    - name: Install elemental
      shell: bash
      run: |
        cd $(mktemp -d)
        wget -O elemental.tar.gz "https://github.com/${{ inputs.repository }}/releases/download/${{ inputs.version }}/elemental-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch}}.tar.gz"
        tar xzf elemental.tar.gz
        sudo mv ./elemental /usr/local/bin
